### ISSUE TITLE
no crypto module?

### ISSUE THREAD

**Issue by OneGoogus** [athombv/com.athom.homeyscript#35]
Hi

Im trying to fetch some api values from a website, but im needed to login in first.
But in order to login, it require me to encrypt the body with hmac-sha256 for login.

But when im trying to use crypto in order to login, the console reply: 

> ❌ Script Error
> ⚠️ ReferenceError: crypto is not defined
>     at HMac-test.js:1:14
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

I tried to find a purejs version of hmac to bypass instead, but had no luck.

any chance of supporting crypto?

```
const hmac = crypto.createHmac('sha256', 'test').update('jsonlogin').digest('hex');
console.log(hmac);
```

**Comment by SPopenko** [comment]
@HomeyTeam is it possible to update the script app and add crypto module as a base since it's pretty common for external API to ask users generate signature for the requests. It would be really useful.  Thanks in advance.
