### ISSUE TITLE
Error using Homey.devices.updateDevice

### ISSUE THREAD

**Issue by XeroxQ** [athombv/com.athom.homeyscript#44]
Hey,

I get an error in HomeyScript (through code or cards) when trying to update a device:
❌ Script Error
⚠️ TypeError: Cannot read properties of null (reading 'approximation')
    at Function.value (/node_modules/athom-api/dist/index.js:1:863528)
    at o.<anonymous> (/node_modules/athom-api/dist/index.js:1:847079)
    at x (/node_modules/athom-api/dist/index.js:1:346562)
    at Generator.u._invoke (/node_modules/athom-api/dist/index.js:1:346357)
    at Generator.e.<computed> [as next] (/node_modules/athom-api/dist/index.js:1:346741)
    at t (/node_modules/athom-api/dist/index.js:1:9216)
    at /node_modules/athom-api/dist/index.js:1:9312
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

------------- Code to get the error
var args = ['2487293a-f67b-422f-a31a-7d3ef18270fd']; //ID of a device
let d =await Homey.devices.getDevice({id:args[0]});
//d.name = 'test'; // even without changing anything, we get an error.
return await Homey.devices.updateDevice({id:args[0], device:d});

**Comment by XeroxQ** [comment]
Issue was not sending the device back, but create a new one.
After that, i get no access rights.
